-- Complete the neighborhood catalog from the supplied April 3, 2019 Redmond map.
-- Generated from steppe/scripts/maps/source-labels.json (263 printed labels).
-- Existing IDs, names, slugs and member references are preserved; four existing
-- choices absent from the source map remain. No boundary/verification decisions.
-- Owner: apply in the SQL editor before merging the map/list address release.
begin;
insert into public.neighborhoods (slug, name) values
  ('27-elm', '27 Elm'),
  ('27th-park', '27th Park'),
  ('alder-glen', 'Alder Glen'),
  ('amber-springs', 'Amber Springs'),
  ('antler-crossing', 'Antler Crossing'),
  ('antler-point', 'Antler Point'),
  ('antler-ridge', 'Antler Ridge'),
  ('arnett', 'Arnett'),
  ('aspen-creek', 'Aspen Creek'),
  ('aspen-valley', 'Aspen Valley'),
  ('aspen-winds', 'Aspen Winds'),
  ('atop-the-summit', 'Atop the Summit'),
  ('autumnglen', 'Autumnglen'),
  ('ayres-acres', 'Ayres Acres'),
  ('baker-park', 'Baker Park'),
  ('ballpark-view', 'Ballpark View'),
  ('banta-acres', 'Banta Acres'),
  ('bartel', 'Bartel'),
  ('basking-ridge', 'Basking Ridge'),
  ('bella-sera', 'Bella Sera'),
  ('bella-vista', 'Bella Vista'),
  ('bentwood-estates', 'Bentwood Estates'),
  ('berni-s-subdivision', 'Berni''s Subdivision'),
  ('black-hawk', 'Black Hawk'),
  ('blue-sky-addition', 'Blue Sky Addition'),
  ('boulder-brook', 'Boulder Brook'),
  ('boulder-brook-condos', 'Boulder Brook Condos'),
  ('braydon-park', 'Braydon Park'),
  ('brierwood', 'Brierwood'),
  ('brooktree', 'Brooktree'),
  ('brown-s-additions', 'Brown''s Additions'),
  ('buckner', 'Buckner'),
  ('canyon-crossing', 'Canyon Crossing'),
  ('canyon-point-east', 'Canyon Point East'),
  ('canyon-point-estates', 'Canyon Point Estates'),
  ('canyon-ranch', 'Canyon Ranch'),
  ('canyon-rim-village', 'Canyon Rim Village'),
  ('canyon-view', 'Canyon View'),
  ('canyon-villas', 'Canyon Villas'),
  ('carly-meadows', 'Carly Meadows'),
  ('cascade-view-allotment', 'Cascade View Allotment'),
  ('cascade-view-estates', 'Cascade View Estates'),
  ('cascade-west', 'Cascade West'),
  ('casper-mobile-acres', 'Casper Mobile Acres'),
  ('cedar-creek-village-condos', 'Cedar Creek Village Condos'),
  ('cedar-village', 'Cedar Village'),
  ('century-estates', 'Century Estates'),
  ('chelsea-square', 'Chelsea Square'),
  ('cliffs', 'Cliffs'),
  ('coho-crossing', 'Coho Crossing'),
  ('coho-run', 'Coho Run'),
  ('collins-addition', 'Collins Addition'),
  ('cook-crossing-condo', 'Cook Crossing Condo'),
  ('copper-ridge', 'Copper Ridge'),
  ('corks-westside', 'Corks Westside'),
  ('corks-westside-addition', 'Corks Westside Addition'),
  ('country-park', 'Country Park'),
  ('crane-meadow', 'Crane Meadow'),
  ('credenda', 'Credenda'),
  ('credenda-subdivision', 'Credenda Subdivision'),
  ('crossings-at-metolius', 'Crossings at Metolius'),
  ('curry-addition', 'Curry Addition'),
  ('dana-butler', 'Dana-Butler'),
  ('deer-crossing', 'Deer Crossing'),
  ('dehmc-acre', 'Dehmc Acre'),
  ('desert-valley', 'Desert Valley'),
  ('desert-valley-east', 'Desert Valley East'),
  ('diamond-bar-ranch', 'Diamond Bar Ranch'),
  ('dobson-slocum-acreage', 'Dobson-Slocum Acreage'),
  ('dorsch-acres', 'Dorsch Acres'),
  ('dove-meadow', 'Dove Meadow'),
  ('eagle-park', 'Eagle Park'),
  ('east-rim', 'East Rim'),
  ('eastside-city', 'Eastside City'),
  ('echo-rim-estates', 'Echo Rim Estates'),
  ('ehret-s-first-addition', 'Ehret''s First Addition'),
  ('ellinger-s-addition', 'Ellinger''s Addition'),
  ('emerald-view-estates', 'Emerald View Estates'),
  ('emerald-villa', 'Emerald Villa'),
  ('emily-estates', 'Emily Estates'),
  ('evansville', 'Evansville'),
  ('fair-acres', 'Fair Acres'),
  ('fair-acres-addition', 'Fair Acres Addition'),
  ('fairgrounds-condo-plaza', 'Fairgrounds Condo Plaza'),
  ('fairhaven', 'Fairhaven'),
  ('fairhaven-crossing', 'Fairhaven Crossing'),
  ('fairhaven-vista', 'Fairhaven Vista'),
  ('fairhaven-vista-p-u-d', 'Fairhaven Vista P.U.D.'),
  ('fieldstone', 'Fieldstone'),
  ('fieldstone-crossing', 'Fieldstone Crossing'),
  ('fieldstone-south', 'Fieldstone South'),
  ('forked-horn-butte', 'Forked Horn Butte'),
  ('forrest-commons', 'Forrest Commons'),
  ('frank-s-landing', 'Frank''s Landing'),
  ('goodrich-subdivision', 'Goodrich Subdivision'),
  ('gray-butte-estates', 'Gray Butte Estates'),
  ('greens-at-redmond', 'Greens at Redmond'),
  ('guy-s-acres', 'Guy''s Acres'),
  ('hall', 'Hall'),
  ('harold-s-addition', 'Harold''s Addition'),
  ('harry-ranch-estates', 'Harry Ranch Estates'),
  ('hawley-estates', 'Hawley Estates'),
  ('hayden-acres', 'Hayden Acres'),
  ('hayden-ranch-estates', 'Hayden Ranch Estates'),
  ('hayden-square', 'Hayden Square'),
  ('hayden-view', 'Hayden View'),
  ('hayden-village', 'Hayden Village'),
  ('heierman', 'Heierman'),
  ('heierman-mccormick', 'Heierman-McCormick'),
  ('heritage-ranch', 'Heritage Ranch'),
  ('hester', 'Hester'),
  ('hi-country-estates', 'Hi-Country Estates'),
  ('hidden-valley-mobile-estates', 'Hidden Valley Mobile Estates'),
  ('hill-crest', 'Hill Crest'),
  ('home-depot-station', 'Home Depot Station'),
  ('howell-acres', 'Howell Acres'),
  ('howell-s-hill-top-acres', 'Howell''s Hill Top Acres'),
  ('howell-s-river-rim', 'Howell''s River Rim'),
  ('hunt-s-three-sisters-view', 'Hunt''s Three Sisters View'),
  ('innovation-park', 'Innovation Park'),
  ('jean-meadows', 'Jean Meadows'),
  ('jefferson-view-allotment', 'Jefferson View Allotment'),
  ('jensen-tracts', 'Jensen Tracts'),
  ('johnson-acres', 'Johnson Acres'),
  ('julina-park', 'Julina Park'),
  ('juniper-glen', 'Juniper Glen'),
  ('juniper-glen-north', 'Juniper Glen North'),
  ('juniper-hill', 'Juniper Hill'),
  ('juniper-meadows', 'Juniper Meadows'),
  ('juniper-vista', 'Juniper Vista'),
  ('justin-glen', 'Justin Glen'),
  ('kayla-village', 'Kayla Village'),
  ('kenyons-acreage', 'Kenyons Acreage'),
  ('kian-canyon', 'Kian Canyon'),
  ('kian-west', 'Kian West'),
  ('larch-meadows', 'Larch Meadows'),
  ('lawson-crossing', 'Lawson Crossing'),
  ('lone-juniper-estates', 'Lone Juniper Estates'),
  ('majestic-ridge', 'Majestic Ridge'),
  ('makena-view-estates', 'Makena View Estates'),
  ('maple-meadows', 'Maple Meadows'),
  ('maplewood', 'Maplewood'),
  ('mckenzie-rim-estates', 'McKenzie Rim Estates'),
  ('mckenzie-s-meadow', 'McKenzie''s Meadow'),
  ('meadowbrook-estates', 'Meadowbrook Estates'),
  ('meadowlark-estates', 'Meadowlark Estates'),
  ('megan-park', 'Megan Park'),
  ('melrose-park', 'Melrose Park'),
  ('metts-subdivision', 'Metts Subdivision'),
  ('mida-addition', 'Mida Addition'),
  ('mountain-gardens', 'Mountain Gardens'),
  ('mountain-glenn', 'Mountain Glenn'),
  ('mountain-view-addition', 'Mountain View Addition'),
  ('myers-acreage', 'Myers Acreage'),
  ('negus-villas', 'Negus Villas'),
  ('newberry-village', 'Newberry Village'),
  ('ni-lah-sha', 'Ni-Lah-Sha'),
  ('nolan-s-addition', 'Nolan''s Addition'),
  ('north-canyon-estates', 'North Canyon Estates'),
  ('north-rim', 'North Rim'),
  ('oak-hills', 'Oak Hills'),
  ('obsidian-estates', 'Obsidian Estates'),
  ('obsidian-meadows', 'Obsidian Meadows'),
  ('obsidian-trails', 'Obsidian Trails'),
  ('orchard-knoll', 'Orchard Knoll'),
  ('oregon-trunk-addition', 'Oregon Trunk Addition'),
  ('p-r-i-d-e-estates', 'P.R.I.D.E. Estates'),
  ('park-place-estates', 'Park Place Estates'),
  ('parkland', 'Parkland'),
  ('parkland-townhomes', 'Parkland Townhomes'),
  ('parkway-addition', 'Parkway Addition'),
  ('pine-tree-meadows', 'Pine Tree Meadows'),
  ('planerville', 'Planerville'),
  ('pleasant-view', 'Pleasant View'),
  ('poco-bella', 'Poco Bella'),
  ('prairie-crossing', 'Prairie Crossing'),
  ('quartz-canyon-tracts', 'Quartz Canyon Tracts'),
  ('quince-avenue', 'Quince Avenue'),
  ('railey-s-place', 'Railey''s Place'),
  ('railway-addition', 'Railway Addition'),
  ('ranch-way-acres', 'Ranch Way Acres'),
  ('ranchette-view-estates', 'Ranchette View Estates'),
  ('red-hawk', 'Red Hawk'),
  ('red-bar-estates', 'Red-Bar Estates'),
  ('redmond-acres', 'Redmond Acres'),
  ('redmond-addition', 'Redmond Addition'),
  ('redmond-heights', 'Redmond Heights'),
  ('redmond-town-center', 'Redmond Town Center'),
  ('redside', 'Redside'),
  ('redtail-ridge', 'Redtail Ridge'),
  ('reindeer-woods', 'Reindeer Woods'),
  ('remington-arms', 'Remington Arms'),
  ('rennolds-acres', 'Rennolds Acres'),
  ('ridgepointe', 'Ridgepointe'),
  ('rim-rock-acres', 'Rim Rock Acres'),
  ('rim-view-subdivision', 'Rim View Subdivision'),
  ('rimrock-estates', 'Rimrock Estates'),
  ('roberts-addition', 'Roberts Addition'),
  ('rock-crest', 'Rock Crest'),
  ('sage-townhomes-condo', 'Sage Townhomes Condo'),
  ('salmon-park', 'Salmon Park'),
  ('salmon-run', 'Salmon Run'),
  ('sarasoda-court', 'Sarasoda Court'),
  ('savannah-estates', 'Savannah Estates'),
  ('shadow-glen-estates', 'Shadow Glen Estates'),
  ('sierra-vista', 'Sierra Vista'),
  ('sisters-view-estates', 'Sisters View Estates'),
  ('six-peaks', 'Six Peaks'),
  ('skidmore-s-subdivision', 'Skidmore''s Subdivision'),
  ('skyline-ridge', 'Skyline Ridge'),
  ('sothman-s-addition', 'Sothman''s Addition'),
  ('south-gate-estates', 'South Gate Estates'),
  ('south-heights-addition', 'South Heights Addition'),
  ('south-moreland-acres', 'South Moreland Acres'),
  ('south-end-acreage', 'South-End Acreage'),
  ('steelhead-estates', 'Steelhead Estates'),
  ('sterling-pointe', 'Sterling Pointe'),
  ('stonehedge-on-the-rim', 'Stonehedge on the Rim'),
  ('stonehedge-south-phase-one', 'Stonehedge South Phase One'),
  ('stonehedge-west', 'Stonehedge West'),
  ('summer-creek', 'Summer Creek'),
  ('summerfield', 'Summerfield'),
  ('summerhaven', 'Summerhaven'),
  ('summit', 'Summit'),
  ('summit-crest', 'Summit Crest'),
  ('sunnyside', 'Sunnyside'),
  ('sunnyside-addition', 'Sunnyside Addition'),
  ('sunscape', 'Sunscape'),
  ('sunset-summit', 'Sunset Summit'),
  ('sunshine', 'Sunshine'),
  ('sunshine-addition', 'Sunshine Addition'),
  ('taylor-s-addition', 'Taylor''s Addition'),
  ('the-meadows', 'The Meadows'),
  ('the-sage', 'The Sage'),
  ('timber-acres', 'Timber Acres'),
  ('timber-estates', 'Timber Estates'),
  ('timber-flats', 'Timber Flats'),
  ('timber-view-condos', 'Timber View Condos'),
  ('timbers', 'Timbers'),
  ('torryn-s-addition', 'Torryn''s Addition'),
  ('townhomes-at-quince-village', 'Townhomes at Quince Village'),
  ('triple-ridge', 'Triple Ridge'),
  ('two-bar-estates', 'Two Bar Estates'),
  ('umatilla-heights', 'Umatilla Heights'),
  ('umatilla-villa', 'Umatilla Villa'),
  ('valleyview', 'Valleyview'),
  ('view-acres', 'View Acres'),
  ('village-pointe', 'Village Pointe'),
  ('village-square', 'Village Square'),
  ('vista-dorado', 'Vista Dorado'),
  ('vista-meadows', 'Vista Meadows'),
  ('volcano-place', 'Volcano Place'),
  ('volcano-subdivision', 'Volcano Subdivision'),
  ('waterway-addition-to-redmond', 'Waterway Addition to Redmond'),
  ('waverly', 'Waverly'),
  ('weckerle-heights', 'Weckerle Heights'),
  ('west-canyon-estates', 'West Canyon Estates'),
  ('whitehorse', 'Whitehorse'),
  ('wildflower', 'Wildflower'),
  ('willow-springs', 'Willow Springs'),
  ('windhaven-park', 'Windhaven Park'),
  ('windrow-acres', 'Windrow Acres'),
  ('windsong', 'Windsong')
on conflict (slug) do nothing;
commit;
