-- Add names present in the county's 2026-10-01 Redmond subdivision snapshot.
-- 67 additions; no existing ID, name, slug, profile, or membership is changed.
-- Generated with Supabase CLI, moved into the repository's numbered sequence.
-- Owner applies in SQL editor before merging the outline/catalog release.
begin;
insert into public.neighborhoods (slug, name) values
  ('121-west', '121 West'),
  ('21st-street-condominiums', '21st Street Condominiums'),
  ('3-t-industrial-park', '3-T Industrial Park'),
  ('44-north-estates', '44 North Estates'),
  ('airport-business-center', 'Airport Business Center'),
  ('airport-industrial-park-west', 'Airport Industrial Park-West'),
  ('antelope-flatts', 'Antelope Flatts'),
  ('antler-meadows', 'Antler Meadows'),
  ('blairs-lot-3-subdivision', 'Blairs Lot 3 Subdivision'),
  ('canyon-ridge', 'Canyon Ridge'),
  ('canyon-trails', 'Canyon Trails'),
  ('central-cascade-business-park-condominiums', 'Central Cascade Business Park Condominiums'),
  ('cornerstone-professional-park', 'Cornerstone Professional Park'),
  ('culley', 'Culley'),
  ('desert-rise-industrial-park', 'Desert Rise Industrial Park'),
  ('dry-canyon', 'Dry Canyon'),
  ('elm-park', 'Elm Park'),
  ('fair-acres-ii', 'Fair Acres II'),
  ('fairgrounds-business-park', 'Fairgrounds Business Park'),
  ('feather-ridge', 'Feather Ridge'),
  ('hammerstone-industrial-park', 'Hammerstone Industrial Park'),
  ('hearthstone', 'Hearthstone'),
  ('josie-meadows', 'Josie Meadows'),
  ('junegrass-meadows', 'Junegrass Meadows'),
  ('juniper-canyon-living', 'Juniper Canyon Living'),
  ('juniper-lane', 'Juniper Lane'),
  ('kalama-park', 'Kalama Park'),
  ('kampstra', 'Kampstra'),
  ('kelley', 'Kelley'),
  ('kenai-business-park', 'Kenai Business Park'),
  ('kingwood-crossing', 'Kingwood Crossing'),
  ('korbin-meadows', 'Korbin Meadows'),
  ('lavawood', 'Lavawood'),
  ('leeanne-acres', 'Leeanne Acres'),
  ('lindsay-industrial-park', 'Lindsay Industrial Park'),
  ('links-condominiums-at-the-greens', 'Links Condominiums at the Greens'),
  ('mirage', 'Mirage'),
  ('murphy-industrial-tracts', 'Murphy Industrial Tracts'),
  ('north-trailside', 'North Trailside'),
  ('obsidian-lofts', 'Obsidian Lofts'),
  ('owen-ridge', 'Owen Ridge'),
  ('parker-s-place', 'Parker''s Place'),
  ('pasco-industrial-park', 'Pasco Industrial Park'),
  ('pioneer-business-park', 'Pioneer Business Park'),
  ('pioneer-park-industrial-condominiums', 'Pioneer Park Industrial Condominiums'),
  ('prairie-crossing-east', 'Prairie Crossing East'),
  ('redmond-business-park', 'Redmond Business Park'),
  ('redmond-retail-park', 'Redmond Retail Park'),
  ('redmond-townsite', 'Redmond Townsite'),
  ('redmond-townsite-first-addition', 'Redmond Townsite First Addition'),
  ('rimrock-park-place', 'Rimrock Park Place'),
  ('rimview-estates', 'Rimview Estates'),
  ('rooted-at-19th-condominium', 'Rooted at 19th Condominium'),
  ('sage-court', 'Sage Court'),
  ('sego-estates', 'Sego Estates'),
  ('smith-rock-industrial-park', 'Smith Rock Industrial Park'),
  ('starview', 'Starview'),
  ('stearns-subdivision', 'Stearns Subdivision'),
  ('sunrise-condominiums', 'Sunrise Condominiums'),
  ('sunrise-meadows', 'Sunrise Meadows'),
  ('timber-grove-villas', 'Timber Grove Villas'),
  ('virginia-center', 'Virginia Center'),
  ('vista-la-monte-industrial-park', 'Vista La Monte Industrial Park'),
  ('vista-point', 'Vista Point'),
  ('walter-s-views', 'Walter''s Views'),
  ('ward-commons', 'Ward Commons'),
  ('westmount-condominium', 'Westmount Condominium')
on conflict (slug) do nothing;
commit;
