"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser, isModerator } from "@/lib/auth";

/**
 * Mint and revoke invite tokens (migration 0027).
 *
 * NO SERVICE ROLE HERE, ON PURPOSE (ADR §4). Both actions run as the moderator
 * through the ordinary authenticated client, so every write passes the
 * `invite_tokens_manage` policy — `using (is_moderator())` — exactly like any
 * other moderator action. The `isModerator()` checks below are defense in depth
 * and a decent error message; RLS is the gate. Reaching for the admin client
 * would put minting outside the row-level rules and make the audit story
 * "trust the route".
 *
 * `service_role` is confined to `redeem_invite()`, which is a different problem:
 * the redeemer has no session to authorise the write as. Minting always has one.
 *
 * WHAT IS NOT HERE: no way to edit a token's cap, expiry, or label after minting.
 * A card is printed from a token; quietly re-pointing one after distribution
 * would make the paper lie. Mint another and revoke the first.
 */

export type MintResult =
  | { ok: true; token: string }
  | { ok: false; error: "forbidden" | "invalid" | "failed" };

export type RevokeResult = { ok: true } | { ok: false; error: "forbidden" | "failed" };

/** Bounds on one mint action, so a typo cannot print a thousand-use token. */
const MAX_USES_CEILING = 250;
const MAX_DAYS = 365;

/**
 * Mint one capped token and return its string so it can be printed.
 *
 * `created_by` is set from the SERVER's idea of who is calling — never from the
 * request body (CLAUDE.md invariant 2). A client cannot mint a token attributed
 * to someone else because it never supplies the attribution.
 *
 * KNOWN GAP, recorded rather than papered over: the ADR says `created_by` is
 * taken from `auth.uid()` "inside the database", but 0027 ships the column with
 * no default and no trigger, so the value is set here instead. The property that
 * matters — a client cannot choose it — holds either way. Moving it into the
 * database (`default auth.uid()`) belongs in a later migration; 0027 is applied
 * to production and is not editable.
 *
 * The token STRING is generated by the database default (128 bits of
 * gen_random_bytes, hex-encoded). It is never composed here: a token minted from
 * application randomness would be a second source of entropy to audit.
 */
export async function mintInviteToken(input: {
  maxUses: number;
  days: number;
  label: string;
  neighborhoodId: string | null;
}): Promise<MintResult> {
  if (!(await isModerator())) return { ok: false, error: "forbidden" };

  const user = await getCurrentUser();
  if (!user) return { ok: false, error: "forbidden" };

  const maxUses = Math.floor(Number(input.maxUses));
  const days = Math.floor(Number(input.days));
  if (
    !Number.isFinite(maxUses) ||
    maxUses < 1 ||
    maxUses > MAX_USES_CEILING ||
    !Number.isFinite(days) ||
    days < 1 ||
    days > MAX_DAYS
  ) {
    return { ok: false, error: "invalid" };
  }

  const label = input.label.trim().slice(0, 120);
  const expiresAt = new Date(Date.now() + days * 86_400_000).toISOString();

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("invite_tokens")
    .insert({
      max_uses: maxUses,
      expires_at: expiresAt,
      label: label || null,
      created_by: user.id,
      neighborhood_id: input.neighborhoodId || null,
    })
    .select("token")
    .maybeSingle<{ token: string }>();

  if (error || !data?.token) {
    console.error("[invites] mint failed", error?.message);
    return { ok: false, error: "failed" };
  }

  revalidatePath("/protected/invites");
  return { ok: true, token: data.token };
}

/**
 * Stop further redemptions of a token.
 *
 * REVOKING IS NOT UNDOING, and the UI says so. `revoked_at` closes the door for
 * anyone who has not yet walked through it; addresses already written to the
 * allowlist by past redemptions stay there, and accounts already created stay
 * created. A revocation cascade — reaching what a token produced — is prerequisite
 * work for member-minted tokens and is deliberately not built (ADR §5). Promising
 * a cascade in the copy while shipping only the door would be the worse failure.
 *
 * Idempotent: revoking a revoked token is a no-op, because the timestamp is only
 * set where it is currently null. A double-click must not rewrite the moment a
 * decision was made.
 */
export async function revokeInviteToken(id: string): Promise<RevokeResult> {
  if (!(await isModerator())) return { ok: false, error: "forbidden" };

  const supabase = await createClient();
  const { error } = await supabase
    .from("invite_tokens")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", id)
    .is("revoked_at", null);

  if (error) {
    console.error("[invites] revoke failed", error.message);
    return { ok: false, error: "failed" };
  }

  revalidatePath("/protected/invites");
  return { ok: true };
}
